/*
 * Selling Partner API for Easy Ship
 * The Selling Partner API for Easy Ship helps you build applications that help sellers manage and ship Amazon Easy Ship orders.  Your Easy Ship applications can:  * Get available time slots for packages to be scheduled for delivery.  * Schedule, reschedule, and cancel Easy Ship orders.  * Print labels, invoices, and warranties.  See the [Marketplace Support Table](doc:easy-ship-api-v2022-03-23-use-case-guide) for the differences in Easy Ship operations by marketplace.
 *
 * OpenAPI spec version: 2022-03-23
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.easyship;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.model.easyship.OrderItemSerialNumbers;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Item identifier and serial number information.
 */
@ApiModel(description = "Item identifier and serial number information.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-24T13:36:02.735+08:00")
public class Item {
  @SerializedName("orderItemId")
  private String orderItemId = null;

  @SerializedName("orderItemSerialNumbers")
  private OrderItemSerialNumbers orderItemSerialNumbers = null;

  public Item orderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
    return this;
  }

   /**
   * Get orderItemId
   * @return orderItemId
  **/
  @ApiModelProperty(value = "")
  public String getOrderItemId() {
    return orderItemId;
  }

  public void setOrderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
  }

  public Item orderItemSerialNumbers(OrderItemSerialNumbers orderItemSerialNumbers) {
    this.orderItemSerialNumbers = orderItemSerialNumbers;
    return this;
  }

   /**
   * Get orderItemSerialNumbers
   * @return orderItemSerialNumbers
  **/
  @ApiModelProperty(value = "")
  public OrderItemSerialNumbers getOrderItemSerialNumbers() {
    return orderItemSerialNumbers;
  }

  public void setOrderItemSerialNumbers(OrderItemSerialNumbers orderItemSerialNumbers) {
    this.orderItemSerialNumbers = orderItemSerialNumbers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Item item = (Item) o;
    return Objects.equals(this.orderItemId, item.orderItemId) &&
        Objects.equals(this.orderItemSerialNumbers, item.orderItemSerialNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderItemId, orderItemSerialNumbers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item {\n");
    
    sb.append("    orderItemId: ").append(toIndentedString(orderItemId)).append("\n");
    sb.append("    orderItemSerialNumbers: ").append(toIndentedString(orderItemSerialNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

